# The ```*``` idiom
--------------------------------------------------------------

### The ```*``` operator  -- "Rest" of list idiom

In [1]:
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
k = [0, 1]
lk = [l,k]
print('lk:', lk)

data_1, data_2 = [], []
data_1, data_2 = [*lk]
print('d1 len:', len(data_1), ' d2 len:', len(data_1))
print('data_1: ', data_1) 
print('data_2: ', data_2)

# Star idiom
p = [*l, k]; print(p)
p = [l, *k]; print(p)
p = [*l, *k]; print(p)

(l1, l2, *l3) = p
print(l1) # First element
print(l2) # 2nd  element
print(l3) # remainder of list 

lk: [['a', 'b', 'c', 'd', 'e', 'f', 'g'], [0, 1]]
d1 len: 7  d2 len: 7
data_1:  ['a', 'b', 'c', 'd', 'e', 'f', 'g']
data_2:  [0, 1]
['a', 'b', 'c', 'd', 'e', 'f', 'g', [0, 1]]
[['a', 'b', 'c', 'd', 'e', 'f', 'g'], 0, 1]
['a', 'b', 'c', 'd', 'e', 'f', 'g', 0, 1]
a
b
['c', 'd', 'e', 'f', 'g', 0, 1]


In [2]:
import numpy as np
  
def memory_sizer(mem_size, input_shape):
    
    z = np.zeros((mem_size, *input_shape))
    
    print(f'mem-size: {mem_size}')
    print(f'input size: {input_shape}')
    print(f'Shape of Z: {z.shape}')
    print(30*'-')
    print(z)
    print(60*'=')

In [3]:
print(memory_sizer(3, (2,4)))
print(memory_sizer(3, (2,)))

mem-size: 3
input size: (2, 4)
Shape of Z: (3, 2, 4)
------------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
None
mem-size: 3
input size: (2,)
Shape of Z: (3, 2)
------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
None


In [4]:
A = np.random.randint(low=30, high=200, size=10)
print(A)
batch = np.random.choice(10, 4, replace=False)
print(batch)
print(A[batch])

[198  44 188  97 167  88 119 184 125 147]
[0 5 8 3]
[198  88 125  97]


In [5]:
def add(x, y):
    z = x + y
    return (x,y,z)

print(add(10, 20))

(10, 20, 30)


In [6]:
A = np.random.randint(50, size=(4, 2, 3))
A

array([[[28,  3, 22],
        [ 8, 47, 43]],

       [[19, 36,  3],
        [15, 46,  2]],

       [[34, 10, 32],
        [47, 42,  9]],

       [[13,  1, 32],
        [12, 26, 21]]])

In [7]:
print(A.shape); print(A); print(60*'-')

B = A[:, -1, 2]; print(B.shape); print(B)

(4, 2, 3)
[[[28  3 22]
  [ 8 47 43]]

 [[19 36  3]
  [15 46  2]]

 [[34 10 32]
  [47 42  9]]

 [[13  1 32]
  [12 26 21]]]
------------------------------------------------------------
(4,)
[43  2  9 21]
